### ISSUE TITLE
Thow a new "IllegalArgumentException" in StructureFactory

### ISSUE THREAD

**Issue by mpmenne** [ben2525/Mario#2]
Hey Ben,

Dude, your code looks really great.  

In the StructureFactory I noticed that you're returning a null if the param doesn't match "P".

Returning nulls from methods is sometimes bad because you have to put null checks throughout your code.

One way you can deal with this is by throwing an "IllegalArgumentException".  I throw these exceptions whenever I have a method that is passed invalid data.

**Comment by ben2525** [comment]
Duly noted and modified.  No longer returning null.
Thanks, Mike!.
